### ISSUE TITLE
blobtools command line view produces graph with no labels

### ISSUE THREAD

**Issue by alexrvandam** [genomehubs/blobtoolkit#203]
Dear Blobtoolkit user group and developers,

First, blobtoolkit is a great set of programs, and the plots in particular are intuitive and beautiful, especially the snail plot. 

My question/predicament is that I am completely stuck trying to get blobtools view to add labels to the keys and axis of the graphs. I would be grateful for any suggestions on how I fix this? Let me explain some of the things I have tried over the last few days to troubleshoot.

I checked the meta.json and it is VALID according to the blobtools validation tool. I also tried opening up a jupyter notebook to see if I could produce the graphs via the firefox GUI but the cluster I am on does not allow this type of interaction with firefox for security reasons, or I am simply not familiar enough with jupyter. I also tried a number of different ways to run blobtools view, and ways of adding in the data a step at a time vs all together in a bunch of different combinations to see if that was it. I also tried to examine and fix my version of the blobtools.py but I see that it must be communicating with a larger library of python and rust which is I am not familiar enough with and I am not sure where to start there, or which file could be producing the error so I can go in and fix it?

I also tried setting things up on my personal macbook but it is an early 2015 model and in any case it simply had too many conflicts/deficiencies with Xcode and other such mac programs to make this possible. In any case I would like to use the command line tool via linux to do the graphing as it is quite close to a very nice looking figure and this might be of use to other folks who also want to do this via the command line.

I believe I am using blobtools v4.3.3, installed using mamba then pip to install, and am running on a newer linux cluster.  I setup blobtools using data from my own blast and minimap2/samtools alignments, via: 

######## blobtools add
blobtools add --hits coffee_blastn_megablast_to_big_blastdb.pre.filt.try4.out --hits-cols 1=qseqid,2=staxids,3=bitscore,4=sseqid,5=evalue,6=qstart,7=qend --taxrule bestsum --hit-count 1 --evalue 1e-25 --taxdump /ocean/projects/bio220058p/vandam/Cosmo/taxdump --fasta coffee.purged.m20.free.masked.copy.fa --cov coffee_purged_m20_free_masked_copy_mini_try3_rmdup.bam --busco ../purged__m20_out/run_insecta_odb10/full_table.tsv --taxid 251759 --create blobDir3
####### blobtools view and plot
blobtools view --view snail --plot --out blobDir3 blobDir3
#######

No errors were reported when running the above commands.

I attach the results from the graphing and the meta.json file.

![blobDir3 blob circle](https://github.com/blobtoolkit/blobtoolkit/assets/41234756/f9c88e88-83a5-4c53-98f2-caf8bb05c097)
![blobDir3 snail](https://github.com/blobtoolkit/blobtoolkit/assets/41234756/a42d8048-962c-433e-9685-d3a8fcfd3b5d)

And I attach the meta.json file with some file paths redacted: 

[meta.redactedpaths.json](https://github.com/blobtoolkit/blobtoolkit/files/14014006/meta.redactedpaths.json)

I hope I have given enough information to make my questions clear and to hopefully produce some suggestions. Thank you very much time in advance for helping to answer my questions.

Alex

**Comment by rjchallis** [comment]
I think I've tracked this down to the library that renders the svg to png not being able to lookup font names unless there is an exact match. As a workaround you could output svg images by passing the `--format svg` option to blobtools view. The text should render on these when you open them in an image editor or a browser window.

I will update the code to add an option to specify the font family manually which will get around the font name lookup issue. I've just run a quick test of this to check it works on a container with limited fonts available so can make sure it is available in the next release

**Comment by alexrvandam** [comment]
Yes! the --format svg did the trick. Thank you Richard for helping me with my questions, these are great programs and I happy that my small problem could be of some use to the community. Best wishes, Alex

**Comment by rjchallis** [comment]
Glad the svg options has worked for you. The png text should now be working better on most systems with the latest release (4.3.4), if you want to give that a try. In case it still fails to pick up a system font, you can also set an environment variable `FONT_FAMILY` to the name of any font you have installed to use that for the plots, e.g. 

```
FONT_FAMILY="Courier New" blobtools view --plot /path/to/dataset
```
